# ConfigMap d√≥nde se definen variables de entorno
# See: https://kubernetes.io/docs/concepts/configuration/configmap/

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_NAME: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
